"""Small, safe provenance contract for TradingAgents runs.

The framework produces research/advisory decisions.  A caller must be able to
tell which information boundary and graph configuration produced a report
without persisting provider URLs, API keys, or other credentials.  This module
keeps that contract independent from LangGraph's checkpoint implementation so
it can also be consumed by report and integration tooling.
"""

from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Mapping, Sequence
from datetime import datetime
from typing import Any

PROVENANCE_SCHEMA = "tradingagents-run-provenance-v1"
_FINGERPRINT_RE = re.compile(r"^[0-9a-f]{16}$")

# Only values that affect the graph/research behavior and are safe to persist.
# Endpoint, credentials, and vendor configuration are deliberately excluded.
_GRAPH_CONFIG_KEYS = (
    "max_debate_rounds",
    "max_risk_discuss_rounds",
    "max_recur_limit",
    "holding_period_days",
    "output_language",
    "checkpoint_enabled",
)


def _stable_hash(value: Mapping[str, Any]) -> str:
    payload = json.dumps(value, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


def build_run_provenance(
    *,
    ticker: str,
    trade_date: str,
    asset_type: str,
    selected_analysts: Sequence[str],
    config: Mapping[str, Any],
    route_fingerprint: str,
    portfolio_fingerprint: str = "none",
) -> dict[str, Any]:
    """Build an audit-safe manifest for a completed advisory run.

    ``route_fingerprint`` is already an opaque digest generated by the graph;
    callers must not pass a raw endpoint or credential.  The returned object is
    JSON-serialisable and intentionally states that this layer has no execution
    capability.  It is metadata only and cannot grant broker authority.
    """
    graph_config = {
        key: config.get(key)
        for key in _GRAPH_CONFIG_KEYS
        if key in config
    }
    graph_config["selected_analysts"] = list(selected_analysts)
    graph_config["asset_type"] = str(asset_type)
    graph_config["portfolio_fingerprint"] = str(portfolio_fingerprint)
    return {
        "schema_version": PROVENANCE_SCHEMA,
        "data_cutoff": str(trade_date),
        "universe": [str(ticker).strip()],
        "asset_type": str(asset_type),
        "route_fingerprint": str(route_fingerprint),
        "graph_config_hash": _stable_hash(graph_config),
        "execution_capability": False,
        "mode": "advisory",
    }


def validate_run_provenance(
    manifest: Mapping[str, Any], *, expected_ticker: str | None = None
) -> None:
    """Fail closed when a persisted run manifest breaks the provenance contract.

    Reports are consumed by later review and replay tooling, so a malformed or
    execution-capable manifest must never be written as if it were trusted
    metadata.  The validator is deliberately deterministic: it validates the
    canonical shape and safe scalar values without comparing against the wall
    clock or a live provider.

    ``expected_ticker`` is optional because callers may validate a manifest
    before they know the report directory.  When supplied, it binds the
    single-universe manifest to the report being written.
    """
    if not isinstance(manifest, Mapping):
        raise ValueError("run_provenance must be a mapping")

    required = {
        "schema_version",
        "data_cutoff",
        "universe",
        "asset_type",
        "route_fingerprint",
        "graph_config_hash",
        "execution_capability",
        "mode",
    }
    missing = sorted(required.difference(manifest))
    if missing:
        raise ValueError(f"run_provenance is missing required fields: {', '.join(missing)}")

    if manifest["schema_version"] != PROVENANCE_SCHEMA:
        raise ValueError(
            f"unsupported run_provenance schema: {manifest['schema_version']!r}"
        )

    cutoff = manifest["data_cutoff"]
    if not isinstance(cutoff, str):
        raise ValueError("run_provenance.data_cutoff must be a YYYY-MM-DD string")
    try:
        canonical_cutoff = datetime.strptime(cutoff, "%Y-%m-%d").strftime("%Y-%m-%d")
    except ValueError as exc:
        raise ValueError("run_provenance.data_cutoff must be a YYYY-MM-DD string") from exc
    if cutoff != canonical_cutoff:
        raise ValueError("run_provenance.data_cutoff must be canonical YYYY-MM-DD")

    universe = manifest["universe"]
    if isinstance(universe, (str, bytes)) or not isinstance(universe, Sequence) or not universe:
        raise ValueError("run_provenance.universe must be a non-empty sequence")
    for ticker in universe:
        if not isinstance(ticker, str) or not ticker.strip() or ticker != ticker.strip():
            raise ValueError("run_provenance.universe entries must be non-empty strings")
        if any(ord(char) < 32 for char in ticker):
            raise ValueError("run_provenance.universe entries must not contain control characters")
    if expected_ticker is not None and (
        len(universe) != 1 or universe[0] != str(expected_ticker).strip()
    ):
        raise ValueError("run_provenance.universe does not match the report ticker")

    asset_type = manifest["asset_type"]
    if not isinstance(asset_type, str) or not asset_type.strip() or asset_type != asset_type.strip():
        raise ValueError("run_provenance.asset_type must be a non-empty string")

    for field in ("route_fingerprint", "graph_config_hash"):
        value = manifest[field]
        if not isinstance(value, str) or not _FINGERPRINT_RE.fullmatch(value):
            raise ValueError(f"run_provenance.{field} must be a 16-character lowercase hex digest")

    if manifest["execution_capability"] is not False:
        raise ValueError("run_provenance.execution_capability must remain false")
    if manifest["mode"] != "advisory":
        raise ValueError("run_provenance.mode must be advisory")

    try:
        json.dumps(manifest, ensure_ascii=False, allow_nan=False)
    except (TypeError, ValueError) as exc:
        raise ValueError("run_provenance must be JSON-safe") from exc

