"""Small, safe provenance contract for TradingAgents runs.

The framework produces research/advisory decisions.  A caller must be able to
tell which information boundary and graph configuration produced a report
without persisting provider URLs, API keys, or other credentials.  This module
keeps that contract independent from LangGraph's checkpoint implementation so
it can also be consumed by report and integration tooling.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping, Sequence
from typing import Any

PROVENANCE_SCHEMA = "tradingagents-run-provenance-v1"

# Only values that affect the graph/research behavior and are safe to persist.
# Endpoint, credentials, and vendor configuration are deliberately excluded.
_GRAPH_CONFIG_KEYS = (
    "max_debate_rounds",
    "max_risk_discuss_rounds",
    "max_recur_limit",
    "holding_period_days",
    "output_language",
    "checkpoint_enabled",
)


def _stable_hash(value: Mapping[str, Any]) -> str:
    payload = json.dumps(value, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


def build_run_provenance(
    *,
    ticker: str,
    trade_date: str,
    asset_type: str,
    selected_analysts: Sequence[str],
    config: Mapping[str, Any],
    route_fingerprint: str,
    portfolio_fingerprint: str = "none",
) -> dict[str, Any]:
    """Build an audit-safe manifest for a completed advisory run.

    ``route_fingerprint`` is already an opaque digest generated by the graph;
    callers must not pass a raw endpoint or credential.  The returned object is
    JSON-serialisable and intentionally states that this layer has no execution
    capability.  It is metadata only and cannot grant broker authority.
    """
    graph_config = {
        key: config.get(key)
        for key in _GRAPH_CONFIG_KEYS
        if key in config
    }
    graph_config["selected_analysts"] = list(selected_analysts)
    graph_config["asset_type"] = str(asset_type)
    graph_config["portfolio_fingerprint"] = str(portfolio_fingerprint)
    return {
        "schema_version": PROVENANCE_SCHEMA,
        "data_cutoff": str(trade_date),
        "universe": [str(ticker).strip()],
        "asset_type": str(asset_type),
        "route_fingerprint": str(route_fingerprint),
        "graph_config_hash": _stable_hash(graph_config),
        "execution_capability": False,
        "mode": "advisory",
    }

